### PR TITLE
Create NatureWalkPlusPlus.md

### PR DESCRIPTION
**Pull request by PotNoodl**
add new texture pack

### CODE REVIEW

**Comment by PotNoodl** [comment]
oh damn, i forgot to properly link it, 2 secs

**Comment by PotNoodl** [comment]
actually, hold off from merging it yet, i need to test it first

**Review by ProFireDev — CHANGES_REQUESTED** [review]
everything looks fine, but did you ever finish testing?

otherwise it looks good to merge

**Review by ProFireDev — APPROVED** [review]
reviewed because I assume its been tested

**Comment by PotNoodl** [comment]
> everything looks fine, but did you ever finish testing?
> 
> otherwise it looks good to merge

yeah all looks good

**Review by nyakase — APPROVED** [review]

**Comment by ProFireDev** [comment]
woo, that took awhile lol

**Comment by PotNoodl** [comment]
> woo, that took awhile lol

yeah, oops

**Pull request merged**
